import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import { Lato } from 'next/font/google'
import { frFR } from '@clerk/localizations'

const inter = Lato({ 
  subsets: ['latin'], 
  weight: ["100","400", "700"]})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider localization={frFR}>
      <html lang="fr">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
